// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

// `define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
// `define ENABLE_CLOCK2
// `define ENABLE_SDRAM
`define ENABLE_HEX0 
`define ENABLE_HEX1 
`define ENABLE_HEX2 
`define ENABLE_HEX3 
`define ENABLE_HEX4 
`define ENABLE_HEX5 
`define ENABLE_KEY 
`define ENABLE_LED 
`define ENABLE_SW 
`define ENABLE_VGA
// `define ENABLE_ACCELEROMETER
// `define ENABLE_ARDUINO
// `define ENABLE_GPIO

module DE10_LITE_Golden_Top (

    //////////// ADC CLOCK: 3.3-V LVTTL //////////
`ifdef ENABLE_ADC_CLOCK
    input ADC_CLK_10,
`endif
    //////////// CLOCK 1: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK1
    input MAX10_CLK1_50,
`endif
    //////////// CLOCK 2: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK2
    input MAX10_CLK2_50,
`endif

    //////////// SDRAM: 3.3-V LVTTL //////////
`ifdef ENABLE_SDRAM
    output [12:0] DRAM_ADDR,   // Address
    output [ 1:0] DRAM_BA,     // Bank select address
    output        DRAM_CAS_N,  // Column address strobe
    output        DRAM_CKE,    // Clock enable
    output        DRAM_CLK,    // System clock
    output        DRAM_CS_N,   // Chip select
    inout  [15:0] DRAM_DQ,     // Data I/O
    output        DRAM_LDQM,   // x16 Lower Byte, I/O Mask
    output        DRAM_RAS_N,  // Row address strobe
    output        DRAM_UDQM,   // x16 Upper Byte, I/O Mask
    output        DRAM_WE_N,   // Write enable
`endif

    //////////// SEG7: 3.3-V LVTTL //////////
`ifdef ENABLE_HEX0
    output [7:0] HEX0,
`endif
`ifdef ENABLE_HEX1
    output [7:0] HEX1,
`endif
`ifdef ENABLE_HEX2
    output [7:0] HEX2,
`endif
`ifdef ENABLE_HEX3
    output [7:0] HEX3,
`endif
`ifdef ENABLE_HEX4
    output [7:0] HEX4,
`endif
`ifdef ENABLE_HEX5
    output [7:0] HEX5,
`endif

    //////////// KEY: 3.3 V SCHMITT TRIGGER //////////
`ifdef ENABLE_KEY
    input [1:0] KEY,
`endif

    //////////// LED: 3.3-V LVTTL //////////
`ifdef ENABLE_LED
    output [9:0] LEDR,
`endif

    //////////// SW: 3.3-V LVTTL //////////
`ifdef ENABLE_SW
    input [9:0] SW,
`endif

    //////////// VGA: 3.3-V LVTTL //////////
`ifdef ENABLE_VGA
    output [3:0] VGA_B,
    output [3:0] VGA_G,
    output       VGA_HS,
    output [3:0] VGA_R,
    output       VGA_VS
`endif

    //////////// Accelerometer: 3.3-V LVTTL //////////
`ifdef ENABLE_ACCELEROMETER
    output       GSENSOR_CS_N,
    input  [2:1] GSENSOR_INT,
    output       GSENSOR_SCLK,
    inout        GSENSOR_SDI,
    inout        GSENSOR_SDO,
`endif

    //////////// Arduino: 3.3-V LVTTL //////////
`ifdef ENABLE_ARDUINO
    inout [15:0] ARDUINO_IO,
    inout        ARDUINO_RESET_N,
`endif

    //////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
`ifdef ENABLE_GPIO
    inout [35:0] GPIO
`endif
);

  //=======================================================
  //  REG/WIRE declarations
  //=======================================================
  //
  wire        clk_50;
  wire [23:0] seg_dig;
  wire        VGA_CTRL_CLK;
  wire        clk_25;
  wire        locked;

  //=======================================================
  //  Structural coding
  //=======================================================

  assign clk_50 = MAX10_CLK1_50;

  reg  [3:0] rst_cnt = 4'h0;
  wire       rst = ~rst_cnt[3];
  always @(negedge clk_25)
    if (~KEY[0] | ~locked) rst_cnt <= 4'h0;
    else if (rst) rst_cnt <= rst_cnt + 1;

  pll u0 (
      .inclk0(clk_50),
      .locked(locked),
      .c0(clk_25)
  );

  seg6 u1 (
      .iDIG (seg_dig),
      .oSEG0(HEX0),
      .oSEG1(HEX1),
      .oSEG2(HEX2),
      .oSEG3(HEX3),
      .oSEG4(HEX4),
      .oSEG5(HEX5)
  );

  vga u2 (
      .iRST(rst),
      .iCLK(clk_25),
      .oHS(VGA_HS),
      .oVS(VGA_VS),
      .oVGA_B(VGA_B),
      .oVGA_G(VGA_G),
      .oVGA_R(VGA_R)
  );

  hack u3 (
      .iRST(rst),
      .iCLK(clk_25),
      .iBUT_n(KEY[1]),
      .iSW(SW),
      .oLED(LEDR),
      .oSEG(seg_dig)
  );

endmodule
