// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Mon Jun 16 21:43:58 2025

HACK HACK_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RST(RST_sig) ,	// input  RST_sig
	.BUT(BUT_sig) ,	// input [1:0] BUT_sig
	.instruction(instruction_sig) ,	// input [15:0] instruction_sig
	.inRAM(inRAM_sig) ,	// input [15:0] inRAM_sig
	.LED(LED_sig) ,	// output [1:0] LED_sig
	.RAM_ADDR(RAM_ADDR_sig) ,	// output [15:0] RAM_ADDR_sig
	.pc(pc_sig) ,	// output [15:0] pc_sig
	.RAM_WREN(RAM_WREN_sig) 	// output  RAM_WREN_sig
);

